### PR TITLE
V7 compatibility package

### PR DESCRIPTION
**Pull request by dve**
I started to breakout a compatibility package of touchscreen like in the core vaadin. What do you think about it?

### CODE REVIEW

**Comment by mstahv** [comment]
Looks like a good approach to me!

There is one issue to tackle though: the Directory don't properly support multi module Maven projects. So it might be best to leave out parent project declarations (and duplicate some pom.xml declarations). Then the compatibility package could be introduced as an other add-on in the Directory.

**Comment by dve** [comment]
Ok, just two separate projects - do you know how to adjust .travis.yml then?

**Comment by mstahv** [comment]
I think it could work so that there would be one pom.xml on top level, defining two sub modules, but the sub modules pom.xml files don't refer to the parent project at all. I think travis does mvn install on top level and that should propagate to sub modules even though they would be standalone projects.

**Comment by dve** [comment]
@mstahv  could you please review the changes for Switch, because I'm not sure about `imidiate` in v8 - it has gone and is the default?

**Comment by mstahv** [comment]
It is gone and immediate by default.

**Comment by mstahv** [comment]
Looks good to me! 

Let's see how release plugin works with this setup though, might need to make the compatibility package for the directory manually. But I guess there shouldn't be too many changes for the compatibility package at all.

**Comment by mstahv** [comment]
Do you still see obvious changes or should I try cutting a release later today?

**Comment by dve** [comment]
There are still 474 errors if I remove compatibility packages from the dependencies

**Comment by mstahv** [comment]
:-) OK, maybe then let's try to get rid of those and cut the next release then.

**Comment by dve** [comment]
Shall I create a new pull request for the changes, or just push to the old branch?

**Comment by dve** [comment]
Can you please take a look at `TouchKitBundleLoaderFactory` I don't realy understand what it's doing so its a bit hard to port.

**Comment by mstahv** [comment]
I actually have no idea how github works there, I'd assume you can use the same branch and create a new pull request.

**Comment by mstahv** [comment]
I'll try to look into TouchKitBundleLoaderFacktory, it is probably built by me originally.

**Pull request merged**
